# -*- coding: utf-8 -*-
"""Grade de 2025 ja interpretada: {turma: {(dia, tempo):
[(codigo, professor), ...]}}. Gerado por limpar_grade_2025.py
a partir de grade_2sem_2025.py (texto bruto do OCR).
"""

GRADE_2025 = {'10C1': {(1, 1): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (1, 2): [('pred', 'ACo')],
          (1, 3): [('ing', 'PaH')],
          (1, 4): [('fis', 'VSi')],
          (1, 6): [('mat', 'HRiIA308')],
          (1, 7): [('qui', 'CAI')],
          (2, 1): [('ing', 'PaH')],
          (2, 3): [('art', 'Dei'), ('mus', 'DeBr')],
          (2, 4): [('art', 'Joa')],
          (2, 5): [('port', 'Deb')],
          (2, 6): [('qui', 'CAI')],
          (2, 7): [('bio', 'Raq')],
          (2, 9): [('his', 'ALu')],
          (2, 10): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (2, 11): [('mat', 'BrSa')],
          (3, 1): [('bio', 'Raq')],
          (3, 2): [('geo', 'Mlo')],
          (3, 3): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (3, 4): [('GL', 'EFr'), ('GL', 'Car'), ('GL', 'Swa')],
          (3, 5): [('port', 'AMu')],
          (3, 6): [('elet', 'cDiS'), ('elet', 'SJuA105')],
          (3, 7): [('mat', 'BrSa')],
          (3, 9): [('apoio', 'EFr')],
          (4, 1): [('elet', 'VSi'), ('elet', 'Mio')],
          (4, 2): [('port', 'AMu')],
          (4, 3): [('mat', 'BrSa')],
          (4, 4): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (4, 5): [('ing', 'PaH')],
          (4, 6): [('bio', 'Raq')],
          (4, 8): [('esp', 'ADo')],
          (4, 9): [('esp', 'Ron')],
          (4, 10): [('mat', 'HRiA308')],
          (4, 11): [('his', 'ALu')],
          (5, 1): [('GL', 'EFr'), ('GL', 'Car'), ('GL', 'Swa')],
          (5, 2): [('soc', 'Kle')],
          (5, 3): [('elet', 'CAI'), ('elet', 'cLAn')],
          (5, 4): [('fil', 'LAn')],
          (5, 5): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (5, 6): [('geo', 'Mlo')],
          (5, 7): [('port', 'Deb')]},
 '10C2': {(1, 1): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (1, 2): [('ing', 'Vir')],
          (1, 4): [('mat', 'HRiI')],
          (1, 5): [('pred', 'ACo')],
          (1, 6): [('fis', 'VSiIA317')],
          (2, 1): [('port', 'DebA317')],
          (2, 2): [('his', 'ALu')],
          (2, 3): [('art', 'Dei'), ('mus', 'DeBr')],
          (2, 4): [('art', 'Joa')],
          (2, 5): [('mat', 'BrSa')],
          (2, 6): [('port', 'DebA317')],
          (2, 7): [('mat', 'BrSa')],
          (2, 9): [('bio', 'Raq')],
          (2, 10): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (2, 11): [('qui', 'CAIA317')],
          (3, 1): [('his', 'AlLu')],
          (3, 2): [('bio', 'Raq')],
          (3, 3): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (3, 4): [('GL', 'EFr'), ('GL', 'Car'), ('GL', 'Swa')],
          (3, 5): [('mat', 'BrSa')],
          (3, 6): [('elet', 'cDiS'), ('elet', 'SJuA105')],
          (3, 7): [('fil', 'LAn')],
          (3, 9): [('apoio', 'EFrA308')],
          (4, 1): [('elet', 'VSi'), ('elet', 'Mio')],
          (4, 2): [('soc', 'Kle')],
          (4, 3): [('geo', 'Mlo')],
          (4, 4): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (4, 5): [('ing', 'Vir')],
          (4, 6): [('port', 'AMU')],
          (4, 8): [('esp', 'ADo')],
          (4, 10): [('bio', 'Rag')],
          (4, 11): [('mat', 'HRiIA317')],
          (5, 1): [('GL', 'EFr'), ('GL', 'Car'), ('GL', 'Swa')],
          (5, 2): [('geo', 'Mlo')],
          (5, 3): [('elet', 'CAI'), ('elet', 'cLAn')],
          (5, 4): [('port', 'AMu')],
          (5, 5): [('DaF', 'Swa'), ('DaF', 'EFr'), ('DaF', 'SGa')],
          (5, 6): [('qui', 'CAIA317')],
          (5, 7): [('ing', 'Vir')]},
 '11C1': {(1, 1): [('bio', 'Ale')],
          (1, 3): [('geo', 'Mar')],
          (1, 4): [('DaF', 'Swa')],
          (1, 5): [('DaF', 'SGa')],
          (1, 6): [('ing', 'PaH')],
          (1, 7): [('pred', 'Raf')],
          (2, 1): [('fis', 'Cadu')],
          (2, 2): [('bio', 'Ale')],
          (2, 3): [('pred', 'Raf')],
          (2, 4): [('GL', 'SGa'), ('GL', 'Swa')],
          (2, 5): [('art', 'Dei'), ('mus', 'DeBr')],
          (2, 6): [('art', 'Joa')],
          (2, 8): [('mat', 'BrSa')],
          (2, 10): [('his', 'Wag')],
          (2, 11): [('DaF', 'Swa'), ('DaF', 'SGa')],
          (3, 1): [('elet', 'Fab'), ('elet', 'Wag')],
          (3, 2): [('elet', 'Cad')],
          (3, 3): [('port', 'MFo')],
          (3, 4): [('mat', 'BrSa')],
          (3, 5): [('qui', 'Fab')],
          (3, 6): [('DaF', 'Swa'), ('DaF', 'SGa')],
          (3, 7): [('elet', 'Ale'), ('elet', 'Mar'), ('elet', 'Bre')],
          (3, 9): [('fis', 'Cadu')],
          (3, 11): [('geo', 'Mar')],
          (4, 1): [('mat', 'JJ')],
          (4, 3): [('port', 'MFo')],
          (4, 4): [('soc', 'Kle')],
          (4, 5): [('DaF', 'Swa'), ('DaF', 'SGa')],
          (4, 6): [('GL', 'SGa'), ('GL', 'Swa')],
          (4, 7): [('ing', 'PaH')],
          (4, 9): [('port', 'Jana')],
          (4, 10): [('esp', 'ADo')],
          (5, 1): [('elet', 'Ale'), ('elet', 'Mar'), ('elet', 'Bre')],
          (5, 2): [('qui', 'Fab')],
          (5, 3): [('his', 'Wag')],
          (5, 4): [('ing', 'PaH')],
          (5, 5): [('his', 'Wag')],
          (5, 6): [('fil', 'LAn')],
          (5, 7): [('ing', 'PaH')]},
 '11C2': {(1, 1): [('ing', 'PaH')],
          (1, 3): [('port', 'MFo')],
          (1, 4): [('DaF', 'CBu'), ('DaF', 'EFr')],
          (1, 5): [('GL', 'CBu'), ('GL', 'EFr')],
          (1, 6): [('pred', 'Raf')],
          (1, 7): [('geo', 'Mar')],
          (2, 1): [('pred', 'Raf')],
          (2, 2): [('mat', 'JJA313')],
          (2, 3): [('mat', 'BrSa')],
          (2, 4): [('DaF', 'CBu'), ('DaF', 'EFr')],
          (2, 5): [('art', 'Dei'), ('mus', 'DeBr')],
          (2, 6): [('art', 'Joa')],
          (2, 8): [('fis', 'Cadu')],
          (2, 10): [('bio', 'Rag')],
          (2, 11): [('his', 'Wag')],
          (3, 1): [('elet', 'Fab'), ('elet', 'Wag')],
          (3, 2): [('elet', 'Cad')],
          (3, 3): [('mat', 'BrSa')],
          (3, 4): [('bio', 'Raq')],
          (3, 5): [('his', 'Wag')],
          (3, 6): [('fis', 'Cadu')],
          (3, 7): [('elet', 'Ale'), ('elet', 'Mar'), ('elet', 'Bre')],
          (3, 9): [('geo', 'Mar')],
          (3, 10): [('DaF', 'CBu')],
          (3, 11): [('DaF', 'EFr')],
          (4, 1): [('port', 'MFo')],
          (4, 2): [('port', 'Jana')],
          (4, 3): [('mat', 'JJ')],
          (4, 4): [('mat', 'BrSa')],
          (4, 5): [('DaF', 'CBu'), ('DaF', 'EFr')],
          (4, 6): [('ing', 'Pah')],
          (4, 7): [('soc', 'Kle')],
          (4, 9): [('bio', 'Rag')],
          (5, 1): [('elet', 'Ale'), ('elet', 'Mar'), ('elet', 'Bre')],
          (5, 2): [('his', 'Wag')],
          (5, 3): [('qui', 'Fab')],
          (5, 4): [('GL', 'CBu'), ('GL', 'EFr')],
          (5, 5): [('fil', 'LAn')],
          (5, 6): [('ing', 'Pah')],
          (5, 7): [('qui', 'Fab')]},
 '12C1': {(1, 1): [('geo', 'Mar')],
          (1, 3): [('bio', 'Ale')],
          (1, 5): [('ing', 'PaH')],
          (1, 6): [('DaF', 'Swa')],
          (1, 7): [('DaF', 'CBu')],
          (2, 1): [('his', 'Ver')],
          (2, 2): [('elet', 'CAI'), ('elet', 'Cad')],
          (2, 3): [('elet', 'Ver')],
          (2, 4): [('fis', 'Cadu')],
          (2, 5): [('mat', 'JJ')],
          (2, 6): [('DaF', 'Swa'), ('DaF', 'CBu')],
          (2, 7): [('ing', 'PaH')],
          (2, 9): [('bio', 'Ale')],
          (2, 10): [('qui', 'CAI')],
          (2, 11): [('port', 'Deb')],
          (3, 1): [('mat', 'Bre')],
          (3, 2): [('geo', 'Mar')],
          (3, 3): [('his', 'Ver')],
          (3, 5): [('fis', 'Cadu')],
          (3, 6): [('elet', 'Bre'), ('elet', 'Ale'), ('elet', 'Mar')],
          (3, 8): [('DaF', 'Swa'), ('DaF', 'CBu')],
          (3, 9): [('port', 'Deb')],
          (3, 10): [('esp', 'ADo')],
          (3, 11): [('esp', 'Ron')],
          (4, 1): [('mat', 'Bre')],
          (4, 2): [('ing', 'PaH')],
          (4, 3): [('art', 'Dei'), ('mus', 'DeBr')],
          (4, 4): [('art', 'Joa')],
          (4, 5): [('port', 'Deb')],
          (4, 6): [('mat', 'JJ')],
          (4, 7): [('pred', 'AMu')],
          (4, 9): [('GL', 'CBu')],
          (4, 10): [('GL', 'EFr')],
          (4, 11): [('soc', 'Kle')],
          (5, 1): [('fil', 'LAn')],
          (5, 2): [('elet', 'Bre'), ('elet', 'Ale'), ('elet', 'Mar')],
          (5, 3): [('DaF', 'Swa'), ('DaF', 'CBu')],
          (5, 4): [('port', 'Deb')],
          (5, 5): [('qui', 'Fab')],
          (5, 7): [('pred', 'AMu')],
          (5, 10): [('port', 'R')]},
 '9C1': {(1, 1): [('mat', 'HRi')],
         (1, 3): [('esp', 'ADo'), ('esp', 'Ron')],
         (1, 4): [('esp', 'Luc')],
         (1, 5): [('geo', 'Mar')],
         (1, 6): [('DaF', 'Eth')],
         (1, 7): [('DaF', 'SGa')],
         (1, 9): [('apoio', 'Da')],
         (2, 1): [('port', 'ACo')],
         (2, 2): [('DaF', 'Eth'), ('DaF', 'SGa')],
         (2, 3): [('ingT', 'Bea'), ('ingT', 'PaH')],
         (2, 4): [('ingT', 'Vir')],
         (2, 5): [('pred', 'Raf')],
         (2, 6): [('bio', 'Ale')],
         (2, 8): [('pred', 'Raf')],
         (2, 9): [('GL', 'SGa'), ('GL', 'Swa')],
         (2, 10): [('mat', 'HRiA301')],
         (3, 1): [('geo', 'Mar')],
         (3, 2): [('ingT', 'Bea'), ('ingT', 'PaH'), ('ingT', 'Vir')],
         (3, 3): [('port', 'ACo')],
         (3, 4): [('DaF', 'Eth'), ('DaF', 'SGa')],
         (3, 5): [('port', 'ACo')],
         (3, 6): [('qui', 'Fab')],
         (3, 7): [('mat', 'HRiIA301')],
         (4, 1): [('GL', 'SGa'), ('GL', 'Swa')],
         (4, 2): [('tec', 'SJu')],
         (4, 3): [('DaF', 'Eth'), ('DaF', 'SGa')],
         (4, 4): [('his', 'JuLa')],
         (4, 5): [('mus', 'DeBr'), ('art', 'Dei')],
         (4, 6): [('art', 'Joa')],
         (4, 7): [('fis', 'VSiA301')],
         (5, 1): [('tec', 'Fab')],
         (5, 2): [('his', 'Jula')],
         (5, 3): [('mat', 'HRiA301')],
         (5, 4): [('bio', 'Ale')],
         (5, 5): [('ingT', 'Bea'), ('ingT', 'PaH'), ('ingT', 'Vir')],
         (5, 6): [('GL', 'SGa'), ('GL', 'Swa')],
         (5, 7): [('DaF', 'Eth'), ('DaF', 'SGa')]},
 '9C2': {(1, 1): [('fis', 'VSi')],
         (1, 2): [('DaF', 'EFr'), ('DaF', 'Swa')],
         (1, 3): [('esp', 'ADo'), ('esp', 'Ron')],
         (1, 4): [('esp', 'Luc')],
         (1, 5): [('mat', 'HRiIA316')],
         (1, 6): [('geo', 'Mar')],
         (1, 7): [('tec', 'SJu')],
         (1, 9): [('apoio', 'Da')],
         (2, 1): [('GL', 'SGa'), ('GL', 'EFr')],
         (2, 2): [('his', 'Jula')],
         (2, 3): [('ingT', 'Bea'), ('ingT', 'PaH')],
         (2, 4): [('ingT', 'Vir')],
         (2, 5): [('DaF', 'EFr'), ('DaF', 'Swa')],
         (2, 6): [('port', 'ACo')],
         (2, 8): [('mat', 'HRiIA316')],
         (2, 10): [('qui', 'Fab')],
         (3, 1): [('DaF', 'EFr'), ('DaF', 'Swa')],
         (3, 2): [('ingT', 'Bea'), ('ingT', 'PaH'), ('ingT', 'Vir')],
         (3, 3): [('bio', 'Ale')],
         (3, 4): [('port', 'ACo')],
         (3, 5): [('geo', 'Mar')],
         (3, 6): [('port', 'ACo')],
         (3, 7): [('GL', 'SGa'), ('GL', 'EFr')],
         (4, 1): [('tec', 'SJu')],
         (4, 2): [('DaF', 'EFr')],
         (4, 3): [('DaF', 'Swa')],
         (4, 4): [('pred', 'Raf')],
         (4, 5): [('mus', 'DeBr'), ('art', 'Dei')],
         (4, 6): [('art', 'Joa')],
         (4, 7): [('his', 'Jula')],
         (5, 1): [('mat', 'HRiIA316')],
         (5, 3): [('GL', 'SGa'), ('GL', 'EFr')],
         (5, 4): [('pred', 'Raf')],
         (5, 5): [('ingT', 'Bea'), ('ingT', 'PaH'), ('ingT', 'Vir')],
         (5, 6): [('bio', 'Ale')],
         (5, 7): [('DaF', 'EFr'), ('DaF', 'Swa')]}}
