"""initial schema calendario

Revision ID: 48f843bb6ab4
Revises: 
Create Date: 2026-08-10 21:40:11.836247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '48f843bb6ab4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS calendario")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    op.create_table('coordenador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instituicao_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin_instituicao', 'coordenador', name='papelcoordenador'), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['calendario.instituicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='calendario'
    )
    op.create_table('regra_catalogo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instituicao_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=128), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('implementada_solver', sa.Boolean(), nullable=False),
    sa.Column('skill_ref', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['instituicao_id'], ['calendario.instituicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='calendario'
    )
    op.create_table('segmento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coordenador_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['coordenador_id'], ['calendario.coordenador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coordenador_id'),
    schema='calendario'
    )
    op.create_table('grupo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('data_inicio_semestre', sa.Date(), nullable=False),
    sa.Column('data_fim_semestre', sa.Date(), nullable=False),
    sa.Column('datas_segunda_chamada', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conselho_inicio', sa.Date(), nullable=False),
    sa.Column('conselho_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['segmento_id'], ['calendario.segmento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    op.create_index('ix_grupo_segmento_id', 'grupo', ['segmento_id'], unique=False, schema='calendario')
    op.create_table('semestre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmento_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['segmento_id'], ['calendario.segmento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    op.create_index('ix_semestre_segmento_id', 'semestre', ['segmento_id'], unique=False, schema='calendario')
    op.create_table('arquivo_entrada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semestre_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('grade', 'modelo', 'siglas', 'simulados', name='arquivotipo'), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semestre_id'], ['calendario.semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semestre_id', 'tipo', name='uq_arquivo_entrada_semestre_tipo'),
    schema='calendario'
    )
    op.create_table('customizacao_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmento_id', sa.UUID(), nullable=False),
    sa.Column('semestre_id', sa.UUID(), nullable=False),
    sa.Column('instrucao', sa.Text(), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segmento_id'], ['calendario.segmento.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['calendario.semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    op.create_index('ix_customizacao_ia_segmento_id', 'customizacao_ia', ['segmento_id'], unique=False, schema='calendario')
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semestre_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['calendario.semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    op.create_index('ix_job_status_created_at', 'job', ['status', 'created_at'], unique=False, schema='calendario')
    op.create_table('regra_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmento_id', sa.UUID(), nullable=False),
    sa.Column('semestre_id', sa.UUID(), nullable=False),
    sa.Column('regra_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['regra_id'], ['calendario.regra_catalogo.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['calendario.segmento.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['calendario.semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segmento_id', 'semestre_id', 'regra_id', name='uq_regra_config_segmento_semestre_regra'),
    schema='calendario'
    )
    op.create_index('ix_regra_config_segmento_id', 'regra_config', ['segmento_id'], unique=False, schema='calendario')
    op.create_table('turma',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['calendario.grupo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='calendario'
    )
    op.create_table('calendario_gerado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semestre_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('verified', 'published', 'failed', name='calendariostatus'), nullable=False),
    sa.Column('xlsx_blob_path', sa.String(length=1024), nullable=True),
    sa.Column('verificacao_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['calendario.job.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['calendario.semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    schema='calendario'
    )
    op.create_table('relatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('trocas', 'cessoes', 'tabela', 'auxiliar_ia', name='relatoriotipo'), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['calendario_id'], ['calendario.calendario_gerado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='calendario'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorio', schema='calendario')
    op.drop_table('calendario_gerado', schema='calendario')
    op.drop_table('turma', schema='calendario')
    op.drop_index('ix_regra_config_segmento_id', table_name='regra_config', schema='calendario')
    op.drop_table('regra_config', schema='calendario')
    op.drop_index('ix_job_status_created_at', table_name='job', schema='calendario')
    op.drop_table('job', schema='calendario')
    op.drop_index('ix_customizacao_ia_segmento_id', table_name='customizacao_ia', schema='calendario')
    op.drop_table('customizacao_ia', schema='calendario')
    op.drop_table('arquivo_entrada', schema='calendario')
    op.drop_index('ix_semestre_segmento_id', table_name='semestre', schema='calendario')
    op.drop_table('semestre', schema='calendario')
    op.drop_index('ix_grupo_segmento_id', table_name='grupo', schema='calendario')
    op.drop_table('grupo', schema='calendario')
    op.drop_table('segmento', schema='calendario')
    op.drop_table('regra_catalogo', schema='calendario')
    op.drop_table('coordenador', schema='calendario')
    op.drop_table('instituicao', schema='calendario')
    op.execute("DROP TYPE IF EXISTS relatoriotipo")
    op.execute("DROP TYPE IF EXISTS calendariostatus")
    op.execute("DROP TYPE IF EXISTS jobstatus")
    op.execute("DROP TYPE IF EXISTS arquivotipo")
    op.execute("DROP TYPE IF EXISTS papelcoordenador")
    # ### end Alembic commands ###
